### ISSUE TITLE
Tailwind JIT integration

### ISSUE THREAD

**Issue by bdfpplinsinga** [WorkshopCLI/workshop-advanced-gulp#25]
Hee Sam,

Totally not an issue, but im wondering how to integrate Tailwind jit into this workflow? Are you thinking about it? Or do you think this isn't working?

**Comment by salexzee** [comment]
Not sure. Tailwind isn't something I use so I wouldn't be able to tell you how to add it. It's certainly possible. Based on their [documentation](https://github.com/tailwindlabs/tailwindcss-jit) it seems like it's as simple as adding it via `yarn` and then setting up the config with path blobs for your liquid files. You'll need to add the entry file into theme.liquid and you'll probably need to make some updates to the styles gulp task.
