### ISSUE TITLE
New schema is incompatible with the current setting value. 

### ISSUE THREAD

**Issue by akvdcode** [WorkshopCLI/workshop-advanced-gulp#28]
Getting the following error while deploying the theme to the store:

`New schema is incompatible with the current setting value. Invalid value for type in block 'footer-0'. Type must be defined in schema..New schema is incompatible with the current setting value. Invalid value for type in block 'footer-1'. Type must be defined in schema.`

**Comment by salexzee** [comment]
This is not a Workshop issue. It looks like a Shopify error due to an invalid section schema. Closing this out since it's not related to Workshop.
