### ISSUE TITLE
Is it possible to integrate react instead or liquid for frontend with workflow-advanced-gulp?

### ISSUE THREAD

**Issue by akvdcode** [WorkshopCLI/workshop-advanced-gulp#29]
Is it possible to integrate react instead or liquid for frontend with workflow-advanced-gulp?

**Comment by salexzee** [comment]
I'm not sure. I haven't thought much about it. My guess though is that you'd probably be better off building or finding a workflow that's built with React in mind. This workflow is not built for React and so you'd probably have to make some substantial changes to do a full React build. You could probably integrate React into your projects, but as a full replacement for liquid it's not likely with this workflow.
